version: '3.8'

services:
  # Database Service (PostgreSQL)
  db:
    image: postgres:13
    container_name: feedback_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: feedback_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d feedback_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend Service (FastAPI)
  backend:
    build: ./backend
    container_name: feedback_backend
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy

  # Frontend Service (React + Nginx)
  frontend:
    build: ./frontend
    container_name: feedback_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data: